name: Build emulator

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.target.platform }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: StandaloneWindows64
            image: "unityci/editor:windows-2021.3.25f1-windows-il2cpp-1.1.2"
            os: windows-2019
          - platform: Android
            image: "unityci/editor:ubuntu-2021.3.25f1-android-1.1.2"
            os: ubuntu-latest      
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.target.platform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target.platform }}
          customImage: ${{ matrix.target.image }}
          buildName: nofun
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - name: Remove debug information (Windows)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build/${{ matrix.target.platform }}/nofun_BackUpThisFolder_ButDontShipItWithYourGame
          Remove-Item -Recurse -Force build/${{ matrix.target.platform }}/nofun_BurstDebugInformation_DoNotShip
        if: matrix.target.os != 'ubuntu-latest'
      - uses: actions/upload-artifact@v2
        name: Upload artifacts (Android)
        with:
          name: nofun_${{ matrix.target.platform }}
          path: build/${{ matrix.target.platform }}/nofun.apk
        if: matrix.target.platform == 'Android'
      - uses: actions/upload-artifact@v2
        name: Upload artifacts (Non-Android)
        with:
          name: nofun_${{ matrix.target.platform }}
          path: build/${{ matrix.target.platform }}
        if: matrix.target.platform != 'Android'
       
